### ISSUE TITLE
Multi-line key-value pairs do not work correctly for call expressions

### ISSUE THREAD

**Issue by hungrybluedev** [nedpals/tree-sitter-v#16]
The following snippet is valid. However, the parser complains that it is missing a closing parenthesis.
```v
 http.new_response(
    status: .not_found
    text: '404 Not Found'
    header: http.new_header(
        key: .content_type
        value: 'text/plain'
    ).join(headers_close)
)
```
This raises a deeper issue that normal call arguments can also be considered to be seprated by newline rather than commas. This creates a difficulty for the CFG. A syntax change may be necessary.

**Comment by nedpals** [comment]
Solved in https://github.com/nedpals/tree-sitter-v/commit/7f112ce4720492d011a7cca70d1ed736cba9a787
