### ISSUE TITLE
scanner - folder does not exists

### ISSUE THREAD

**Issue by oneslash** [nedpals/tree-sitter-v#19]
hi, I see the following command in packages.json but it doesn't run, I wanted to fix a bug cannot find this :( 

"generate-scanner": "v -shared -skip-unused -o src/scanner.c scanner/",

**Comment by nedpals** [comment]
@oneslash The `generate-scanner` does not work properly at the moment. It was there to see if V can generate a custom scanner for tree-sitter without writing C code so you may ignore that.
